"""Crear tabla de alertas para Isolation Forest

Revision ID: 7584d7f0aa8f
Revises: a550ef90868d
Create Date: 2026-08-19 15:00:52.804422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7584d7f0aa8f'
down_revision: Union[str, Sequence[str], None] = 'a550ef90868d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servidor_id', sa.UUID(), nullable=True),
    sa.Column('mensaje', sa.String(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('tiempo', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_id'), 'alertas', ['id'], unique=False)
    op.create_index(op.f('ix_alertas_servidor_id'), 'alertas', ['servidor_id'], unique=False)
    op.drop_index(op.f('metricas_hardware_tiempo_idx'), table_name='metricas_hardware')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('metricas_hardware_tiempo_idx'), 'metricas_hardware', [sa.literal_column('tiempo DESC')], unique=False)
    op.drop_index(op.f('ix_alertas_servidor_id'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_id'), table_name='alertas')
    op.drop_table('alertas')
    # ### end Alembic commands ###
