"""Migracion Inicial SaaS Multi-Tenant

Revision ID: 83ada48a28f2
Revises: 
Create Date: 2026-08-20 17:34:44.464501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ada48a28f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('servidores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ip_direccion', sa.String(), nullable=False),
    sa.Column('token_auth', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('umbral_cpu', sa.Float(), nullable=True),
    sa.Column('umbral_ram', sa.Float(), nullable=True),
    sa.Column('umbral_disco', sa.Float(), nullable=True),
    sa.Column('umbral_red', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_auth')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servidor_id', sa.UUID(), nullable=True),
    sa.Column('mensaje', sa.String(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('tiempo', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_id'), 'alertas', ['id'], unique=False)
    op.create_index(op.f('ix_alertas_servidor_id'), 'alertas', ['servidor_id'], unique=False)
    op.create_table('metricas_hardware',
    sa.Column('tiempo', sa.DateTime(), nullable=False),
    sa.Column('servidor_id', sa.UUID(), nullable=False),
    sa.Column('cpu_usage_pct', sa.Float(), nullable=True),
    sa.Column('ram_usage_mb', sa.Float(), nullable=True),
    sa.Column('disk_usage_pct', sa.Float(), nullable=True),
    sa.Column('network_latency_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tiempo', 'servidor_id')
    )
    op.create_table('usuario_servidor',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('servidor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'servidor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_servidor')
    op.drop_table('metricas_hardware')
    op.drop_index(op.f('ix_alertas_servidor_id'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_id'), table_name='alertas')
    op.drop_table('alertas')
    op.drop_table('usuarios')
    op.drop_table('servidores')
    op.drop_table('empresas')
    # ### end Alembic commands ###
