"""Creacion inicial de tablas

Revision ID: 89102f3615b7
Revises: 
Create Date: 2026-08-17 17:57:38.415901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89102f3615b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servidores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ip_direccion', sa.String(), nullable=False),
    sa.Column('token_auth', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_auth')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('metricas_hardware',
    sa.Column('tiempo', sa.DateTime(), nullable=False),
    sa.Column('servidor_id', sa.UUID(), nullable=False),
    sa.Column('cpu_usage_pct', sa.Float(), nullable=True),
    sa.Column('ram_usage_mb', sa.Float(), nullable=True),
    sa.Column('disk_usage_pct', sa.Float(), nullable=True),
    sa.Column('network_latency_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidores.id'], ),
    sa.PrimaryKeyConstraint('tiempo', 'servidor_id')
    )
    op.create_table('usuario_servidor',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('servidor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'servidor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_servidor')
    op.drop_table('metricas_hardware')
    op.drop_table('usuarios')
    op.drop_table('servidores')
    # ### end Alembic commands ###
