"""add_alert_preferences_to_usuarios

Revision ID: 92591520e695
Revises: 410a08883ccb
Create Date: 2026-08-26 15:57:09.895369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92591520e695'
down_revision: Union[str, Sequence[str], None] = '410a08883ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('discord_webhook', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('slack_webhook', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('recibir_alertas_email', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'recibir_alertas_email')
    op.drop_column('usuarios', 'slack_webhook')
    op.drop_column('usuarios', 'discord_webhook')
    # ### end Alembic commands ###
