"""add_smtp_settings_to_empresas

Revision ID: acbaa7e46914
Revises: 92591520e695
Create Date: 2026-08-26 16:23:26.816633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acbaa7e46914'
down_revision: Union[str, Sequence[str], None] = '92591520e695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('smtp_host', sa.String(), nullable=True))
    op.add_column('empresas', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('empresas', sa.Column('smtp_user', sa.String(), nullable=True))
    op.add_column('empresas', sa.Column('smtp_password', sa.String(), nullable=True))
    op.add_column('empresas', sa.Column('smtp_from', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'smtp_from')
    op.drop_column('empresas', 'smtp_password')
    op.drop_column('empresas', 'smtp_user')
    op.drop_column('empresas', 'smtp_port')
    op.drop_column('empresas', 'smtp_host')
    # ### end Alembic commands ###
