"""Añadidos umbrales personalizables al servidor

Revision ID: c43834acdec8
Revises: 7584d7f0aa8f
Create Date: 2026-08-19 21:00:05.936204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43834acdec8'
down_revision: Union[str, Sequence[str], None] = '7584d7f0aa8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servidores', sa.Column('umbral_cpu', sa.Float(), nullable=True))
    op.add_column('servidores', sa.Column('umbral_ram', sa.Float(), nullable=True))
    op.add_column('servidores', sa.Column('umbral_disco', sa.Float(), nullable=True))
    op.add_column('servidores', sa.Column('umbral_red', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servidores', 'umbral_red')
    op.drop_column('servidores', 'umbral_disco')
    op.drop_column('servidores', 'umbral_ram')
    op.drop_column('servidores', 'umbral_cpu')
    # ### end Alembic commands ###
