"""anadir_columnas_desglose_disco

Revision ID: c4395b4e9223
Revises: 83ada48a28f2
Create Date: 2026-08-21 21:48:29.088135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4395b4e9223'
down_revision: Union[str, Sequence[str], None] = '83ada48a28f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metricas_hardware', sa.Column('disk_os_gb', sa.Float(), nullable=True))
    op.add_column('metricas_hardware', sa.Column('disk_db_gb', sa.Float(), nullable=True))
    op.add_column('metricas_hardware', sa.Column('disk_logs_gb', sa.Float(), nullable=True))
    op.add_column('metricas_hardware', sa.Column('disk_free_gb', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metricas_hardware', 'disk_free_gb')
    op.drop_column('metricas_hardware', 'disk_logs_gb')
    op.drop_column('metricas_hardware', 'disk_db_gb')
    op.drop_column('metricas_hardware', 'disk_os_gb')
    # ### end Alembic commands ###
